import {
  SiJavascript,
  SiReact,
  SiTailwindcss,
  SiBootstrap,
  SiHtml5,
  SiCss3,
  SiSass,
  SiGit,
  SiGitlab,
  SiNextdotjs,
  SiStrapi,
  SiReacthookform,
  SiDocker,
  SiKubernetes,
} from "react-icons/si";
import { VscAzureDevops } from "react-icons/vsc";

const allSkills = [
  {
    id: 1,
    name: "JavaScript",
    icon: SiJavascript,
    percentage: 90,
    color: "#f7df1e",
  },
  {
    id: 2,
    name: "React",
    icon: SiReact,
    percentage: 85,
    color: "#61dafb",
  },
  {
    id: 3,
    name: "Tailwind CSS",
    icon: SiTailwindcss,
    percentage: 80,
    color: "#38bdf8",
  },
  {
    id: 4,
    name: "Bootstrap",
    icon: SiBootstrap,
    percentage: 75,
    color: "#7952b3",
  },
  {
    id: 5,
    name: "HTML",
    icon: SiHtml5,
    percentage: 95,
    color: "#e34c26",
  },
  {
    id: 6,
    name: "CSS",
    icon: SiCss3,
    percentage: 90,
    color: "#264de4",
  },
  {
    id: 7,
    name: "SCSS",
    icon: SiSass,
    percentage: 85,
    color: "#cd6799",
  },
  {
    id: 8,
    name: "Git",
    icon: SiGit,
    percentage: 85,
    color: "#f05032",
  },
  {
    id: 9,
    name: "GitLab",
    icon: SiGitlab,
    percentage: 80,
    color: "#e24329",
  },
  {
    id: 10,
    name: "Next.js",
    icon: SiNextdotjs,
    percentage: 80,
    color: "#000000",
  },
  {
    id: 11,
    name: "Strapi",
    icon: SiStrapi,
    percentage: 70,
    color: "#4945ff",
  },
  {
    id: 12,
    name: "React Hook Form",
    icon: SiReacthookform,
    percentage: 75,
    color: "#ec5990",
  },
  {
    id: 13,
    name: "Docker",
    icon: SiDocker,
    percentage: 70,
    color: "#2496ed",
  },
  {
    id: 14,
    name: "Kubernetes",
    icon: SiKubernetes,
    percentage: 65,
    color: "#326ce5",
  },
  {
    id: 15,
    name: "DevOps",
    icon: VscAzureDevops,
    percentage: 60,
    color: "#0b5ba1",
  },
];

export default allSkills;
